CREATE TRIGGER TRG_NbPlaces
AFTER INSERT ON INSCRIPTION
FOR EACH ROW
BEGIN
DECLARE PlacesTot INT;
DECLARE PlacesOccup INT;
	SELECT COUNT(NumEv) INTO PlacesOccup 
    FROM INSCRIPTION 
    WHERE INSCRIPTION.NumEv=NEW.NumEv;

	SELECT NbPlaces INTO PlacesTot
	FROM EVENEMENT
	WHERE EVENEMENT.NumEv=NEW.NumEv;
	
	IF (PlacesOccup >= PlacesTot) THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'INSCRIPTION IMPOSSIBLE, IL NE RESTE PAS DE PLACES';
	
	END IF;
END

